backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\User;
use backend\models\Signup;
use backend\models\Login;
use common\models\Parking;

class SiteController extends Controller
{

	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['signup', 'login', 'error'],
						'allow' => true,
					],
					[
						'actions' => [
							'logout',
							'index',
							'all',
							'update',
						],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}

	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex()
	{
		$model = Parking::find()->where(['status' => 0])->orderBy('id desc');
		return $this->render('index', ['model' => $model]);
	}

	public function actionAll()
	{
		$model = Parking::find()->orderBy('id desc');
		return $this->render('all', ['model' => $model]);
	}
	
	public function actionUpdate($id)
	{
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Parking::findIdentity($id);

		$model->status = 1;
		$model->save();
		return $this->redirect(['index']);

	}

	public function actionSignup()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Signup();

		if(isset($_POST['Signup']))
		{
			$model->attributes = Yii::$app->request->post('Signup');
			if($model->validate() && $model->signup())
			{
				return $this->redirect(['index']);
			}
		}

		return $this->render('signup', [
			'model' => $model,
		]);
	}

	public function actionLogin()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Login();

		if( Yii::$app->request->post('Login')) {
			$model->attributes = Yii::$app->request->post('Login');
			if($model->validate()) {
				$user = $model->getUser();

				Yii::$app->user->login($user);

				return $this->goHome();
			}
		}

		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout()
	{
		Yii::$app->user->logout();
		return $this->goHome();
	}
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\Parking;

class SiteController extends Controller
{

	public function behaviors()
	{
		return [];
	}

	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	public function actionIndex()
	{
		$model = new Parking();

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->save();

			$model->code = strtoupper($this->generateRandomString(5) . Yii::$app->db->getLastInsertID());
			$model->status = 0;

			$model->save(false);

			return $this->render('success', [
				'code' => $model->code
			]);
		}

		return $this->render('index', [
			'model' => $model,
		]);
	}

	public function actionExit()
	{
		$model = new Parking();

		if (Yii::$app->request->post()) {
			$model = Parking::find()->where(['code' => Yii::$app->request->post()['Parking']['code']])->one();
			$model->status = 1;
			$model->save(false);

			return $this->render('success-exit', [
				'username' => $model->username
			]);
		}

		return $this->render('exit', [
			'model' => $model,
		]);
	}

	private function generateRandomString($length = 10) {

		$characters = '0123456789abcdefABCDEF';
		$charactersLength = strlen($characters);
		$randomString = '';

		for ($i = 0; $i < $length; $i++) {
			$randomString .= $characters[rand(0, $charactersLength - 1)];
		}

		return $randomString;
	}
}

backend/views/site/all.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;

$this->title = Yii::t('app', 'Автотранспортное хранилище');
$this->params['breadcrumbs'][] = $this->title;
$status = '';
?>
<div class="col-md-12" style="color: black">
	<div class="panel panel-default">
		<br><br><br>
		<div class="panel-heading"><?= $this->title ?></div>
		<div class="panel-body">
			<div class="contact-index">
				<div class="fa-br"></div>
				<br>
				<?php
				$dataProvider = new ActiveDataProvider([
					'query' => $model,
					'pagination' => [
						'pageSize' => 20,
					],
				]);
				echo GridView::widget([
					'dataProvider' => $dataProvider,
					'layout' => "{items}\n{pager}",
					'columns' => [
			// ['class' => 'yii\grid\SerialColumn'],
						'id',
						'username',
						'number',
						'code',
						[
							'label' => 'Статус',
							'attribute' => 'status',
							'format' => 'raw',
							'value' => function($dataProvider){
								return ($dataProvider->status == 0) ? 'На парковке' : 'Выехал';
							},
						],
						[
							'label' => 'Действие',
							'format' => 'raw',
							'value' => function($dataProvider){
								if($dataProvider->status == 0)
									return Html::a("Отметить как выехавший", ['site/update', 'id' => $dataProvider->id]);
								else
									return "Уже выехал";
							},
						],
					],
				]);
				?>

			</div>

		</div>
	</div>
</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;

$this->title = Yii::t('app', 'Автотранспортное хранилище');
$this->params['breadcrumbs'][] = $this->title;
$status = '';
?>
<div class="col-md-12" style="color: black">
	<div class="panel panel-default">
		<br><br><br>
		<div class="panel-heading"><?= $this->title ?></div>
		<div class="panel-body">
			<div class="contact-index">
				<div class="fa-br"></div>
				<br>
				<?php
				$dataProvider = new ActiveDataProvider([
					'query' => $model,
					'pagination' => [
						'pageSize' => 20,
					],
				]);
				echo GridView::widget([
					'dataProvider' => $dataProvider,
					'layout' => "{items}\n{pager}",
					'columns' => [
			// ['class' => 'yii\grid\SerialColumn'],
						'id',
						'username',
						'number',
						'code',
						[
							'label' => 'Статус',
							'attribute' => 'status',
							'format' => 'raw',
							'value' => function($dataProvider){
								return ($dataProvider->status == 0) ? 'На парковке' : 'Выехал';
							},
						],
						[
							'label' => 'Действие',
							'format' => 'raw',
							'value' => function($dataProvider){
								return Html::a("Выехал", ['site/update', 'id' => $dataProvider->id]);
							},
						],
					],
				]);
				?>

			</div>

		</div>
	</div>
</div>

backend/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use developit\captcha\Captcha;

$this->title = Yii::t('app', 'Login');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="content mx-auto">
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="site-login">

    <div class="row">
    <div class="col-12 col-lg-offset-3">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= Html::submitButton(Yii::t('app', 'Войти'), ['class' => 'btn btn-login', 'name' => 'login-button']) ?>
            <?= Html::a("Регистрация", ['site/signup']); ?>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
</div>

backend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="content mx-auto">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
<div class="site-login">

    <div class="row">
         <div class="col-12">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'autocomplete' => 'off']) ?>
                
                <?= $form->field($model, 'email')->textInput(['autocomplete' => 'off']) ?>

                <?= $form->field($model, 'password')->passwordInput(['autocomplete' => 'off']) ?>

                <div class="form-group">
                    <?= Html::submitButton('Регистрация', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
</div>